name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    - name: Deploy in EC2
      env:
        
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        HOSTNAME : ${{ secrets.HOSTNAME  }}
        USER_NAME : ${{ secrets.USER_NAME  }}
        TARGET: ${{ secrets.TARGET_DIR }}
    

      run: |
        
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        #Now we have got the access of EC2 and we will start the deploy .
        cd /home/ubuntu/project/DevOps-AWS-CICD-Project-1 &&
        git checkout master &&
        git fetch --all &&
        git reset --hard origin/dev_linux &&
        git pull origin dev_linux &&
        source trueflowai/bin/activate
        python manage.py runserver
        

